# Generated by Django 2.2.9 on 2021-03-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210227_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=False, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=False, max_length=200, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=False, max_length=200, verbose_name='Group name'),
        ),
    ]
