# Generated by Django 3.1.7 on 2021-04-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210331_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст', max_length=200, verbose_name='Текст'),
        ),
    ]
